---
title: "MS 6"
author: "Rachel Auslander"
date: "3/23/2020"
output: html_document
---

[My final project repo](https://github.com/rachelaus/final_project)

[My Shiny app link](https://rachel-auslander.shinyapps.io/news_and_candidates/)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(twitteR)
library(rvest)
```

```{r reading in data, include = FALSE}
dec26 <- read_dta("ns20191226/ns20191226.dta")
```

```{r filtering data 1, include = FALSE}
nyt <- dec26 %>% 
  select(news_sources_fox, news_sources_cnn, news_sources_npr, vote_2016) %>% filter(news_sources_fox == 1) %>% 
  filter(vote_2016 == 1 | vote_2016 == 2)
```

```{r ages of readers, echo = FALSE}
viewbyage <- dec26 %>%
  
  # selected columns i needed to work with
  
  select(age, news_sources_msnbc, news_sources_cnn, news_sources_facebook, news_sources_fox, news_sources_network, 
news_sources_localtv, news_sources_telemundo, news_sources_npr, news_sources_amtalk, news_sources_new_york_times, 
news_sources_local_newspaper) %>% arrange(age) %>% 
#news_sources_other_TEXT

# levels for new column age category
#mutated and created a new variable rather than overriding a currently existing
# column
mutate(age_range =
case_when(
  between(age, 18, 23) ~ "18-23",
  between(age, 24, 30) ~ "24-30",
  between(age, 31, 55) ~ "31-55",
  between(age, 56, 75) ~ "56-75",
  between(age, 76, 99) ~ "76-99"
)) %>%
  select(-age) %>%
  arrange(age_range) %>%
  group_by(age_range) %>%
  
  # counted readers
  
  summarize(msnbc = sum(news_sources_msnbc == 1), 
            new_york_times = sum(news_sources_new_york_times == 1),
            cnn = sum(news_sources_cnn == 1),
            fb = sum(news_sources_facebook == 1),
            fox = sum(news_sources_fox == 1),
            network_tv = sum(news_sources_network == 1),
            local_tv = sum(news_sources_localtv == 1), 
            telemundo = sum(news_sources_telemundo == 1), 
            npr = sum(news_sources_npr == 1), 
            am_radio = sum(news_sources_amtalk == 1), 
            local_news = sum(news_sources_local_newspaper == 1)
  ) %>%
  
  # pivoted longer to prepare for graphing and get all news source names in
  # a single column
  
  pivot_longer(-age_range, names_to = "news_source", values_to = "num_news")  %>%
  group_by(age_range)
  #pivot_wider(names_from = age_range, values_from = num_news)

# created plot

age_plot <- viewbyage %>%
  ggplot(aes(x = news_source, y = num_news, fill = age_range)) + 
  geom_col() + 
  labs(title = "Ages of readers of each news source", fill = "Age Range", x = "News Source", y = "Number of Readers/Viewers") + theme_classic() + theme(axis.text.x=element_text(angle=45,hjust=1)) +
  
  # renamed x axis labels in order, not the most efficient way but ok for now
  
  scale_x_discrete(labels = c("AM Radio", "CNN", "Facebook", "Fox", "Local News", "Local TV", "MSNBC", "Network TV", "New York Times", "NPR", "Telemundo"))
  
# printed plot

age_plot

```

```{r create graphic, include = FALSE}
ggsave("news_and_candidates/age_plot.png", plot = age_plot)
```